using Microsoft.EntityFrameworkCore;
using Todolist;
var builder = WebApplication.CreateBuilder(); 
var MyAllowSpecificOrigins = "_myAllowSpecificOrigins"; 
builder.Services.AddCors();
builder.Services.AddControllers();
builder.Services.AddEndpointsApiExplorer();
builder.Services.AddSwaggerGen(); 
builder.Services.AddDbContext<ModelDbContext>();
var app = builder.Build(); app.UseSwagger(); 
app.UseSwaggerUI(); 
app.UseDeveloperExceptionPage();
app.UseCors(opt => opt.WithOrigins("http://localhost:3001").AllowAnyMethod().AllowAnyHeader().AllowCredentials()); //app.UseHttpsRedirection();
app.MapControllers();
app.Run();